In [8]:
import numpy as np

In [9]:
np.__version__


'2.3.5'

# Create and Read

### 1D Array

In [10]:
arr1 = np.array([1,2,3,4,5,])
arr1

array([1, 2, 3, 4, 5])

In [11]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(5,)

In [6]:
arr1.dtype


dtype('int64')

In [7]:
arr1.ndim

1

In [8]:
arr1.size

5

### 2D Array

In [9]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 3)

In [12]:
arr2.size

6

### 3D Array

In [17]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,9,8]],[[7,6,5],[4,3,2]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 9, 8]],

       [[7, 6, 5],
        [4, 3, 2]]])

In [21]:
arr3.ndim


3

In [23]:
arr3.shape

(3, 2, 3)

In [25]:
arr3.size

18

## Create Random Array 

In [3]:
rarr = np.random.rand(3,2,3)
rarr

array([[[0.95624591, 0.51965275, 0.39969423],
        [0.48677733, 0.3740801 , 0.53530298]],

       [[0.41303373, 0.21953046, 0.9828422 ],
        [0.83007913, 0.56242834, 0.78776295]],

       [[0.34014725, 0.94510598, 0.36984877],
        [0.37681849, 0.98596178, 0.18540159]]])

In [16]:
zero = np.zeros((3,2,3))
zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr3[0:2]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 9, 8]]])

In [20]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 9, 8]],

       [[7, 6, 5],
        [4, 3, 2]]])

In [21]:
arr3[0][1][1]

np.int64(5)

In [22]:
arr3[0,1,1]

np.int64(5)

## Update and Delete Array

In [25]:
a1 = np.random.rand(2,3,2)
a1

array([[[0.30147677, 0.70528955],
        [0.20017671, 0.9633633 ],
        [0.01143673, 0.68045832]],

       [[0.53129235, 0.27678133],
        [0.70757217, 0.5476174 ],
        [0.76216936, 0.39978876]]])

In [26]:
a2 = np.random.rand(2,3,2)
a2

array([[[0.79894726, 0.15337257],
        [0.94974726, 0.08858509],
        [0.90126355, 0.82556291]],

       [[0.17232945, 0.11233008],
        [0.08929107, 0.98142112],
        [0.26561854, 0.02770848]]])

In [27]:
np.add(a1,a2)

array([[[1.10042403, 0.85866213],
        [1.14992397, 1.0519484 ],
        [0.91270028, 1.50602123]],

       [[0.7036218 , 0.38911141],
        [0.79686324, 1.52903852],
        [1.02778791, 0.42749724]]])

In [29]:
np.multiply(a1,22)

array([[[ 6.63248886, 15.51637013],
        [ 4.40388756, 21.19399271],
        [ 0.25160801, 14.97008297]],

       [[11.68843175,  6.08918932],
        [15.56658781, 12.04758273],
        [16.76772599,  8.79535266]]])

### Statistical Operations

In [30]:
sqrt = np.sqrt(25)

In [31]:
sqrt

np.float64(5.0)

In [32]:
abs = np.abs(-2)
abs

np.int64(2)

In [35]:
power = np.power(2,2)

In [36]:
power

np.int64(4)

In [37]:
log = np.log(25)
log

np.float64(3.2188758248682006)

In [38]:
min = np.min(a1)
min

np.float64(0.01143672770511528)

In [39]:
max = np.max(a1)
max

np.float64(0.9633633048655231)

### Update

In [40]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 9, 8]],

       [[7, 6, 5],
        [4, 3, 2]]])

In [41]:
arr3[0][1][1]

np.int64(5)

In [42]:
arr3[0][1][1]=50

In [43]:
arr3

array([[[ 1,  2,  3],
        [ 4, 50,  6]],

       [[ 7,  8,  9],
        [ 0,  9,  8]],

       [[ 7,  6,  5],
        [ 4,  3,  2]]])

In [44]:
arr3.sort()
arr3

array([[[ 1,  2,  3],
        [ 4,  6, 50]],

       [[ 7,  8,  9],
        [ 0,  8,  9]],

       [[ 5,  6,  7],
        [ 2,  3,  4]]])

### Reshape

In [45]:
arr3.shape

(3, 2, 3)

In [47]:
arr3_reshape = arr3.reshape((2,3,3))
arr3_reshape

array([[[ 1,  2,  3],
        [ 4,  6, 50],
        [ 7,  8,  9]],

       [[ 0,  8,  9],
        [ 5,  6,  7],
        [ 2,  3,  4]]])

In [48]:
arr3_reshape.size

18

In [49]:
arr3_reshape.shape

(2, 3, 3)

### Appending and Inserting 

In [50]:
zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [51]:
# create new Array
new_arr = np.ones((3,2,3))
new_arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [54]:
appd = np.append(zero,new_arr,axis=0)
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [55]:
zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [56]:
new_arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [57]:
inserted_arr = np.insert(zero,1,new_arr,axis=0)
inserted_arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

## Delete

In [59]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.87042035, 0.30436948, 0.37501597],
        [0.65505223, 0.7921949 , 0.94139261]],

       [[0.36529163, 0.7196419 , 0.51208417],
        [0.43683288, 0.92850512, 0.90245453]],

       [[0.56073844, 0.31177566, 0.09183482],
        [0.16038528, 0.28405286, 0.25164067]]])

In [62]:
np.delete(arr4,0,axis=1)

array([[[0.65505223, 0.7921949 , 0.94139261]],

       [[0.43683288, 0.92850512, 0.90245453]],

       [[0.16038528, 0.28405286, 0.25164067]]])